global:
    scrape_interval: 15s
    evaluation_interval: 15s
rule_files:
    - 'record.geth.rules.yml'
scrape_configs:
    - job_name: 'go-ethereum'
      scrape_interval: 10s
      metrics_path: /debug/metrics/prometheus
      static_configs:
        - targets:
            - '127.0.0.1:6060'
          labels:
            chain: ethereum